"""Source-only decisions: no player rows, joins, feature values or model calls."""
from pathlib import Path
import ast,csv,hashlib,json
R=Path(__file__).resolve().parent; W=R.parent
FIELDS={5:'ORtg',28:'porpag',29:'adjoe',46:'drtg',47:'adrtg',48:'dporpag',49:'stops',50:'bpm',51:'obpm',52:'dbpm',53:'gbpm',55:'ogbpm',56:'dgbpm'}
SOURCES=[
 {'id':'torvik_author','url':'https://adamcwisports.blogspot.com/p/data.html','author':'Bart Torvik','relevant_statement_dates':['2020-11-05','2022-05-02','2022-06-06'],'retrieval':'Web tool open and cached find; no local HTML capture','claim':'Author identifies internal bpm as original Myers BPM and gbpm as BPM2.0; warns that some internal statistics are superseded. Author says source layouts from 2010 onward share a layout; 2008/09 may omit blank play-by-play columns.','limitation':'A 2022 explanation does not establish the exact code/coefficients or historical output vintage of the current CSV.'},
 {'id':'kenpom_primer','url':'https://kenpom.com/blog/individual-stats-primer/','author':'Ken Pomeroy','relevant_statement_dates':['2005-09-21'],'retrieval':'Primary page text returned by web search; no archival capture','claim':'Contemporaneous college-statistics primer attributes individual ORtg to Dean Oliver and Basketball on Paper.','limitation':'Confirms the established statistic, not that current Torvik field5 is an unchanged implementation.'},
 {'id':'oliver_ratings','url':'https://www.basketball-reference.com/about/ratings.html','author':'Basketball Reference, documenting Dean Oliver','relevant_statement_dates':['2004'],'date_kind':'Publication year of the named originating book, as stated on the current primary methods page; page publication date unavailable','retrieval':'Primary methods text returned by web search','claim':'ORtg, individual DRtg and defensive Stops are documented box-score constructions from Basketball on Paper. Formula inputs are the player, team and opponents box-score totals and possession/minute estimates.','limitation':'This audit has no original-book pages or Torvik implementation hash; reconstructing these definitions requires all historical denominators and constants.'},
 {'id':'bpm_methods','url':'https://www.basketball-reference.com/about/bpm2.html','author':'Daniel Myers','relevant_statement_dates':['2014','2020-02'],'retrieval':'Direct open failed; primary methods text returned by later web search. Root independently supplied its web-tool retrieval of Regression Basis and appendix; no raw HTML hash is claimed.','claim':'Original BPM appeared in 2014 using a long NBA RAPM regression basis. BPM2 is dated February2020; its regression basis comprises four five-year NBA RAPM datasets spanning1996–97 through2015–16. Position/role coefficients also derive from NBA samples.','limitation':'The precise original release day and Torvik college adaptation/version remain unverified. Root supplied calibration-section evidence beyond this agent’s returned excerpt.'},
 {'id':'bpm_release','url':'https://www.sports-reference.com/blog/2020/02/introducing-bpm-2-0/','author':'Mike Lynch, Sports Reference','relevant_statement_dates':['2020-02-25'],'retrieval':'Primary publisher announcement returned by web search','claim':'Publisher announces replacement of displayed BPM with BPM2.0 on February25,2020.','limitation':'Does not date Torvik adoption.'},
 {'id':'torvik_backfill','url':'https://adamcwisports.blogspot.com/2017/10/','author':'Bart Torvik','relevant_statement_dates':['2017-10'],'retrieval':'Primary monthly archive text returned by web search','claim':'Author reports backfilling team/player advanced statistics through2008 by2017, with weaker older play-by-play coverage.','limitation':'Backfilled season year is not proof that a present-day formula or table existed in2012–14; no exact date/capture for the individual post was obtained.'}
]
rows=[]
for index,field in FIELDS.items():
 r={'raw_zero_based_index':index,'field':field,'admit_current_raw_column':False,'decision':'unresolved_exclude','earliest_definition_evidence':None,'pre2018_formula_decision':None,'walkforward_2012_2013_2014_decision':None,'dependencies':None,'proof_needed':None,'sources':[]}
 if field in ['ORtg','drtg','stops']:
  r.update(decision='conditional_reconstruction_candidate_current_raw_unverified',earliest_definition_evidence='2004 Oliver definition; ORtg independently discussed in a dated2005 college primer',pre2018_formula_decision='Established definition predates freeze; authorize only a pinned reconstruction or proven matching implementation after source dependencies pass',walkforward_2012_2013_2014_decision='Definition predates all folds; each reconstruction must use only college player/team/opponent data available at that fold cutoff',dependencies='College player/team/opponent box scores, minutes, possessions and fixed pre-cutoff Oliver coefficients; no newly fitted NBA coefficient model',proof_needed='Verify field meaning/unit and exact Torvik implementation against a pinned original definition, including possession/free-throw constants and zero denominators. Establish complete historical team/opponent denominators and source cutoff/vintage; do not infer raw-column equivalence from the label.',sources=['oliver_ratings','kenpom_primer'] if field=='ORtg' else ['oliver_ratings'])
 elif field in ['porpag','adjoe','adrtg','dporpag']:
  r.update(earliest_definition_evidence='No dated exact player-level formula established within the bounded primary-source audit',pre2018_formula_decision='Unresolved; exclude',walkforward_2012_2013_2014_decision='Unresolved for every fold; exclude',dependencies='Unverified: player versus team adjusted-rating identity, opponent-strength adjustment, baseline/replacement value, usage/tempo/minutes transformations and estimation sample',proof_needed='Obtain dated author formula and exact raw-field mapping. Trace all strength-of-schedule, replacement and calibration constants to college-only data ending before the relevant cutoff. Do not substitute current team ADJOE descriptions for player field29.',sources=['torvik_author'])
 elif field in ['bpm','obpm','dbpm']:
  r.update(earliest_definition_evidence='Original Myers BPM released in2014; exact day and Torvik adaptation unverified',pre2018_formula_decision='Original method predates2018 in principle; current Torvik version, adaptation and coefficient sample unverified, so exclude',walkforward_2012_2013_2014_decision='2012/2013: original public method postdates these folds. 2014: exact release/cutoff and permitted calibration sample unverified; exclude all three folds.',dependencies='A fitted NBA RAPM coefficient model plus player box scores and team context; offensive/defensive variant mapping in Torvik is not proven by the total-BPM comment',proof_needed='Pin original release date, source code/coefficients and end date of NBA calibration sample; establish exact college adjustment and current raw-column equivalence. Even if legally available by2018, reuse in earlier folds needs a separate time-valid methodological rule.',sources=['bpm_methods','torvik_author'])
 else:
  r.update(decision='exclude_later_formula_vintage_and_unverified_adaptation',earliest_definition_evidence='BPM2 authored February2020; publisher rollout2020-02-25; Torvik author identifies gbpm with BPM2 in2022',pre2018_formula_decision='Exclude: documented formula release follows2018',walkforward_2012_2013_2014_decision='Exclude: formula follows all folds and NBA calibration through2015–16 includes later seasons relative to these folds',dependencies='NBA-fitted BPM2 coefficients, position/role estimation and college team/player inputs; offensive/defensive raw variant mapping remains unverified',proof_needed='A separately registered alternative using only pre-cutoff coefficients could be reconstructed, but it must receive a new feature name and cannot be labeled as validated current GBPM. Need exact Torvik adaptation and release evidence before any later-cutoff use.',sources=['bpm_methods','bpm_release','torvik_author'])
 rows.append(r)
allowlists={}
for short,path in [('context',W/'r8/build_context.py'),('f50',W/'collectors/build_fifty.py')]:
 tree=ast.parse(path.read_text())
 for node in ast.walk(tree):
  if isinstance(node,ast.Assign) and any(isinstance(t,ast.Name) and t.id in ['fields','FIELDS'] for t in node.targets):
   try: allowlists[short]=sorted(ast.literal_eval(node.value))
   except (ValueError,TypeError): pass
 assert set(FIELDS).isdisjoint(allowlists[short]) and 45 not in allowlists[short]
lineage=json.loads((W/'fifty_audit/lineage_audit.json').read_text())
local={'raw_rows_loaded':0,'raw_pick_values_read':False,'current_allowlist_indices':allowlists,'all13_absent_from_both_allowlists':True,'lineage_existing_summary':lineage,'reviewed_file_hashes':{str(p.relative_to(W)):hashlib.sha256(p.read_bytes()).hexdigest() for p in [W/'r8/build_context.py',W/'collectors/build_fifty.py',W/'fifty_audit/lineage_audit.json']},'limitation':'Existing lineage establishes row identity/replay only, not formula or source publication vintage. No player/source data joins were made in this audit.'}
requests=[('open','https://adamcwisports.blogspot.com/p/data.html','success'),('open','https://www.basketball-reference.com/about/bpm2.html','internal_error'),('find_cached','gbpm','success'),('find_cached','PORPAG','no_exact_case_match'),('find_cached','stop','no_match'),('search','site.adamcwisports.blogspot.com PORPAGATU2016','malformed_site_filter_no_formula'),('search','site:basketball-reference.com/about/bpm2.html20141997','irrelevant_results_ignored'),('search','site:adamcwisports.blogspot.com PORPAGATU2016or2015or2014','dated_backfill_found_no_exact_formula'),('search','site:kenpom.com/blog individual offensive rating2004or2005','2005_primary_primer'),('search','PORPAGATU formula Bart Torvik; author_domains','no_dated_exact_formula'),('search','defensive rating stops Oliver; primary_domains','primary_2004_definition_and_formulas'),('search','Box Plus/Minus February20202014; publisher_domains','primary_methods_and2020_announcement')]
(R/'field_decisions.json').write_text(json.dumps(rows,indent=2))
with (R/'field_decisions.csv').open('w') as f:
 writer=csv.DictWriter(f,fieldnames=list(rows[0]));writer.writeheader();writer.writerows([{**r,'sources':'|'.join(r['sources'])} for r in rows])
(R/'sources.json').write_text(json.dumps(SOURCES,indent=2))
(R/'local_source_audit.json').write_text(json.dumps(local,indent=2))
(R/'network_ledger.json').write_text(json.dumps({'limit':12,'operations_including_cached_finds':len(requests),'additional_root_evidence':'Parent supplied existing primary-method retrieval; no extra network request by this agent','requests':[{'ordinal':i+1,'operation':a,'target_or_query':b,'result':c} for i,(a,b,c) in enumerate(requests)]},indent=2))
assert len(rows)==13 and all(not r['admit_current_raw_column'] for r in rows)
assert len([r for r in rows if r['decision'].startswith('conditional')])==3
assert all(i!=45 for i in FIELDS)
print(json.dumps({'fields_audited':13,'current_raw_columns_admitted':0,'conditional_reconstruction_candidates':['ORtg','drtg','stops'],'network_operations_including_cached_finds':12,'raw_player_rows_loaded':0,'new_features_or_models':False},indent=2))
