from pathlib import Path
import json
ROOT=Path(__file__).resolve().parent
r=json.loads((ROOT/'results/test_result.json').read_text())
f=r['aggregate']['full_legacy'];o=r['aggregate']['complete_target_subset']
pct=lambda x: 'undefined' if x is None else f'{100*x:.1f}%'
lines=[f"# Frozen model test: 2019–2025",'',f"The model associated with the 57.9% development result scored **{pct(o['score'])} on the complete-outcome test subset** and **{pct(f['score'])} on the full available benchmark**. These are Spearman rank correlations multiplied by 100, not the percentage of draft positions predicted correctly.",'', '| Draft | Full benchmark | Draft-order baseline | Complete-outcome subset | Players: full / complete | Labels through |','|---|---:|---:|---:|---:|---:|']
for y in r['rows']:
 lines.append(f"| {y['season']} | {pct(y['full_legacy']['score'])} | {pct(y['full_legacy']['draft'])} | {pct(y['complete_target_subset']['score'])} | {y['n_full']} / {y['n_complete_target']} | {y['training']['actual_admitted_label_max']} |")
lines += [f"| Seven-class mean | **{pct(f['score'])}** | **{pct(f['draft'])}** | **{pct(o['score'])}** | {sum(y['n_full']for y in r['rows'])} / {sum(y['n_complete_target']for y in r['rows'])} | — |",'',f"The complete-outcome subset's draft-order baseline was {pct(o['draft'])}. Class scores receive equal weight. The frozen model combines seeds 0, 101 and 202 by equal rank averaging. For comparison with the development headline's mean-of-seed convention, the test mean of individual seed correlations was {pct(o['mean_seed_score'])} on the complete-outcome subset and {pct(f['mean_seed_score'])} on the full available benchmark.",'',"The recipe was selected before this evaluation: s2000_gap1_drafted_h2_E_tabicl16_o0p5. It uses 44 fixed predictors and trains on historically drafted players with two observed NBA-season WAR labels. Nine development fits reproduced the original raw predictions, canonical predictions and model settings exactly. Each test year ran in its own process and isolated filesystem/network namespace, with only that year's input bundle. All seven prediction files were hashed and frozen before the scorer opened any test outcomes. Actual draft position was used only by the scorer for the comparison baseline.",'',"Training labels obey the prediction-year cutoff; missing training outcomes were not zero-filled. The verified calendar currently stops at 2022, so the 2024 and 2025 fits omit otherwise allowable newer training seasons. The original benchmark's outcome horizons are five seasons for 2019–2021, four for 2022, three for 2023, two for 2024 and one for 2025.",'',"The full benchmark retains the inherited scoring treatment in which missing outcome components contribute zero. The complete-outcome subset requires every outcome component for that horizon to be observed, which favors players with sufficient observed career length; it is not full-class accuracy. All predictions were made before this scoring-only mask was applied.",'',"This remains a diagnostic result: the benchmark was repeatedly inspected in earlier work, the original player pool omits some historical draftees, and retrospective college inputs are not fully certified to their original publication dates. It should not be described as a pristine holdout or proof of a leakage-free production model. No test result was used to tune this model or promote a new recipe.",'',f"Prediction freeze: `{r['prediction_freeze_sha256']}`",f"Scored at: {r['scored_at_utc']}",'']
(ROOT/'REPORT.md').write_text('\n'.join(lines))
