from pathlib import Path
import json,hashlib,shutil,itertools
R=Path(__file__).resolve().parent;D=R/'d_reference';shutil.copytree(R.parent/'r9e/d_reference',D,dirs_exist_ok=True,ignore=shutil.ignore_patterns('__pycache__','*.pyc'));shutil.copyfile(D/'queue_runtime.py',R/'queue_runtime.py')
p=json.loads((D/'plan.json').read_text());base=p['baseline_config'];grid={'loss_function':['RMSE','MAE'],'depth':[3,5,7],'learning_rate':[.03,.1],'l2_leaf_reg':[1,10,100],'bagging_temperature':[0,1],'nan_mode':['Min','Max']};variants=[base]
for values in itertools.product(*grid.values()):
 s=dict(zip(grid,values));vid=f"cb_{s['loss_function'].lower()}_d{s['depth']}_lr{s['learning_rate']:g}_l2{s['l2_leaf_reg']}_bag{s['bagging_temperature']}_{s['nan_mode'].lower()}".replace('.','p');variants.append({'id':vid,'kind':'catboost',**s})
plan={k:p[k]for k in ['diagnostic_only','no_confirmation_or_test_scoring','folds','seeds','ordering_policy','baseline_config']}
plan.update(study='R9f CatBoost GPU family and fixed saved-prediction blend diagnostic',reference_id=base['id'],variants=variants,grid=grid,catboost_fixed={'iterations':1200,'task_type':'GPU','devices':'0','thread_count':2,'gpu_ram_part':.18,'random_strength':1,'allow_writing_files':False,'bootstrap_type':'Bayesian','boosting_type':'Plain','use_best_model':False,'verbose':False},tree_checkpoints=[200,600,1200],progress_checkpoint=1200,training_target='Original frozen B yy, unchanged; no target transforms or feature reselection',native_missingness='Train-only CatBoost native Min/Max; no imputation, query-derived borders or pool concatenation',evaluation_rule='Fit1200 trees once per fold without eval_set or early stopping. Predict all three registered ntree_end checkpoints. No score-based stopping or checkpoint selection.',reference_gate='Three original B TabICL32 raw/canonical/score/full-audit reference replays gate interpretation.',blend_diagnostic={'anchors':['drop5_001','none_o0p5_n16'],'alpha_steps':list(range(11)),'alpha':'step/10;0 anchor,1 CatBoost','method':'Within-cohort average-tied rank/n percentiles, exact doubled-integer rank sums; same-seed and fixed equal-three-seed mean endpoints separately. All checkpoints/weights/anchors saved, no favorable-seed selection.'},execution={**p['execution'],'task_count':435},GPU_nondeterminism='Actual CatBoost outputs and seeds retained; no bit-exact CatBoost replay requirement. TabICL baseline exact gates unchanged.',no_model_promotion=True)
assert len(variants)==145
(R/'plan.json').write_text(json.dumps(plan,indent=2,allow_nan=False)+'\n')
files={str(f.relative_to(R)):hashlib.sha256(f.read_bytes()).hexdigest()for f in D.rglob('*')if f.is_file()};files['anchor_records.json']=hashlib.sha256((R/'anchor_records.json').read_bytes()).hexdigest()
(R/'source_manifest.json').write_text(json.dumps({'files':files,'verified_scheduler_sha256':hashlib.sha256((R/'queue_runtime.py').read_bytes()).hexdigest()},indent=2)+'\n')
print('Registered144 CatBoost configurations x3seeds plus3 exact B references=435 tasks.')
